---
- name: Debian | Install keepalived packages.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    allow_unauthenticated: false
    update_cache: true
  become: true
  loop:
    - "keepalived"
    - "psmisc"
...
