---
- name: Delete | import common tasks
  tags:
    - keepalived
    - pbos-infra
  ansible.builtin.import_tasks: "common.yml"

- name: Delete | purge packages
  tags:
    - keepalived
    - pbos-infra
  ansible.builtin.apt:
    name: "{{ item }}"
    purge: true
    state: absent
  loop: "{{ packages }}"
  become: true

- name: Delete | remove directory
  tags:
    - keepalived
    - pbos-infra
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/keepalived
  become: true
...
