---
- name: Setup | copy check_proxy script
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0755"
  loop: "{{ service_script }}"
  become: true
  changed_when: true
  notify:
    - systemctl restart service

- name: Setup | set virtual router id
  ansible.builtin.set_fact:
    keepalived_vrid: "{{ 255 | random }}"
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true

- name: Setup | template keepalived.conf
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.j2' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ service_conf }}"
  become: true
...
