---
- name: Stop | import common tasks
  tags: keepalived
  ansible.builtin.import_tasks: "common.yml"

- name: Stop | stop service
  tags: keepalived
  debug:
    msg: "Stop {{ service_name }} service."
  changed_when: true
  notify:
    - systemctl stop service
...
