---
- name: systemctl restart keepalived.service
  service:
    name: "keepalived.service"
    state: "restarted"
    enabled: true
  become: true
  changed_when: false
  register: restart_keepalived_service
  failed_when: restart_keepalived_service.failed
...
